from setuptools import setup, find_packages

setup(
    name="chromadb",
    version="1.0.0",
    description="Chroma.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Jeff Huber, Anton Troynikov",
    author_email="jeff@trychroma.com, anton@trychroma.com",
    python_requires=">=3.8",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    packages=find_packages(),
    include_package_data=True,
    exclude_package_data={"": ["._*"]},
    install_requires=[
        "build>=1.0.3",
        "pydantic>=1.9",
        "chroma-hnswlib==0.7.6",
        "fastapi>=0.95.2",
        "uvicorn[standard]>=0.18.3",
        "numpy>=1.22.5",
        "posthog>=2.4.0",
        "typing_extensions>=4.5.0",
        "onnxruntime>=1.14.1",
        "opentelemetry-api>=1.2.0",
        "opentelemetry-exporter-otlp-proto-grpc>=1.2.0",
        "opentelemetry-instrumentation-fastapi>=0.41b0",
        "opentelemetry-sdk>=1.2.0",
        "tokenizers>=0.13.2",
        "pypika>=0.48.9",
        "tqdm>=4.65.0",
        "overrides>=7.3.1",
        "importlib-resources",
        "graphlib_backport>=1.0.3; python_version<'3.9'",
        "grpcio>=1.58.0",
        "bcrypt>=4.0.1",
        "typer>=0.9.0",
        "kubernetes>=28.1.0",
        "tenacity>=8.2.3",
        "PyYAML>=6.0.0",
        "mmh3>=4.0.1",
        "orjson>=3.9.12",
        "httpx>=0.27.0",
        "rich>=10.11.0",
    ],
    entry_points={
        "console_scripts": [
            "chroma=chromadb.cli.cli:app",
        ],
    },
)
